# Gitleaks configuration for ShelfBridge
# This file configures what secrets to look for and what to ignore

[allowlist]
# Allowlist patterns for false positives
description = "Allowlist for ShelfBridge project"
paths = [
    # Ignore test files and documentation
    "test/",
    "node_modules/",
    ".*\\.example$",
    "config\\.yaml\\.example",
    "README\\.md",
    ".*\\.md$",
    "\\.gitleaks\\.toml",
]

# Allowlist specific patterns that are false positives
regexes = [
    # Variable names and property access (not actual secrets)
    "user\\.abs_token",
    "user\\.hardcover_token",
    "\\$\\{.*token\\}",
    "\\$\\{.*\\.token\\}",
    "this\\.token",
    "Bearer \\$\\{.*\\}",
    
    # Field names in arrays and objects
    "'abs_token'",
    "'hardcover_token'",
    "\"abs_token\"",
    "\"hardcover_token\"",
    
    # Console log messages showing field names
    "console\\.log.*abs_token.*\\?",
    "console\\.log.*hardcover_token.*\\?",
    
    # Variable assignments from user object
    "= user\\.abs_token",
    "= user\\.hardcover_token",
    
    # Comments and descriptions
    "//.*token",
    "/\\*.*token.*\\*/",
    "description:.*token",
    "description.*API token",
    
    # Test and example values
    "api_key.*example",
    "token.*example",
    "test.*api.*key",
    "mock.*token",
]

# Use default gitleaks rules (much smarter than custom rules)
# These rules look for actual secret patterns, not just variable names
include_default = true 