services:
  shelfbridge:
    image: ghcr.io/rohit-purandare/shelfbridge:latest
    # Uncomment the line below and comment the image line above to build locally
    # build: .
    container_name: shelfbridge
    # Restart policy: "no" prevents restart loops during configuration setup
    # Change to "unless-stopped" after initial configuration is complete
    restart: "no"
    volumes:
      # Named volumes for zero-setup - no local directories required
      - shelfbridge-config:/app/config
      - shelfbridge-data:/app/data
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "node", "src/main.js", "config", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.docker.compose.project=shelfbridge"
      - "com.docker.compose.service=shelfbridge"
    networks:
      - shelfbridge-network

volumes:
  shelfbridge-config:
    driver: local
  shelfbridge-data:
    driver: local

networks:
  shelfbridge-network:
    driver: bridge 