global:
  min_progress_threshold: 5.0
  dry_run: true
  parallel: false
  max_books_to_process: 3

users:
  - id: rpurandare
    abs_url: https://audiobookshelf.rohitp.me/
    abs_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlJZCI6IjI1NDIxNzc0LTMxZWYtNDQ0ZC1hOWExLWQ2Zjk0MDdhYzkxYSIsIm5hbWUiOiJzaGVsZnN5bmMxIiwidHlwZSI6ImFwaSIsImlhdCI6MTc1MjYxNDIxOH0.xBjfIF06MiBXwplkHISN2cRvuiAAhui5mHzOk4oEJ3k
    hardcover_token: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJIYXJkY292ZXIiLCJ2ZXJzaW9uIjoiOCIsImp0aSI6IjkwMTUxMTdkLThkYzUtNDIyOC1hMTIxLTRmMTJjOThjMTQxNCIsImFwcGxpY2F0aW9uSWQiOjIsInN1YiI6IjIxMTQxIiwiYXVkIjoiMSIsImlkIjoiMjExNDEiLCJsb2dnZWRJbiI6dHJ1ZSwiaWF0IjoxNzUyNjE0MjMzLCJleHAiOjE3ODQxNTAyMzMsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciIsIlgtaGFzdXJhLXVzZXItaWQiOiIyMTE0MSJ9LCJ1c2VyIjp7ImlkIjoyMTE0MX19.ITM4b8NuwQ9omRmhCK3jkZJN1qZno0ieHeFGrJCt2uo
