# Pull Request Labeler Workflow
# Purpose: Automatically label pull requests based on changed files
# Triggers: PR opened, synchronized, reopened, or edited
# Configuration: .github/labeler.yml
name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: labeler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      repository-projects: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml
          sync-labels: false
          dot: true
